name: "Dokku Deploy"

on:
  push:
    branches:
      - master

jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}

  deploy-emerald:
    needs: cancel-previous
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: ${{ secrets.EMERALD_DEPLOY_URL }}
          ssh_private_key: ${{ secrets.EMERALD_SSH_KEY }}

  deploy-sapphire:
    needs: cancel-previous
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: ${{ secrets.SAPPHIRE_DEPLOY_URL }}
          ssh_private_key: ${{ secrets.SAPPHIRE_SSH_KEY }}
